# -*- coding: utf-8 -*-
"""AI_exam07_classification_mnist.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12LTnk-57Rw0QblIsM9GWGTaHBfezOwzA

mnist 숫자 분류 모델 만들기~~
"""

import numpy as np
import matplotlib.pyplot as plt
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Flatten
from keras.utils import to_categorical

(X_train, Y_train), (X_test, Y_test) = mnist.load_data()
print(X_train.shape)
print(Y_train.shape)
print(X_test.shape)
print(Y_test.shape)

my_sample = np.random.randint(0, 60000)
print(Y_train[my_sample])
plt.imshow(X_train[my_sample], cmap='gray')
plt.show()
print(X_train[my_sample])

"""데이터 전처리!! 스케일링하자"""

# One Hot Encoding
y_train = to_categorical(Y_train)
y_test = to_categorical(Y_test)

print(Y_train[5000])
print(y_train[5000])

# 픽셀 리스트들을 리스트화
x_train = X_train.reshape(60000, 28 * 28)
x_test = X_test.reshape(10000, 28 * 28)
print(x_train[5000])

# Scaling (Min-Max Scaling)
x_train = x_train / 255
x_test = x_test /255
print(x_train.shape)
print(x_train[5000])

"""모델 만들기!!!"""

model = Sequential()
model.add(Dense(128, input_shape=(784,), activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

fit_hist = model.fit(x_train, y_train, epochs=15, batch_size=512, validation_split=0.2)

score = model.evaluate(x_test, y_test)
print('Final test set accuracy', score[1])

plt.plot(fit_hist.history['loss'], label='Training Loss')
plt.plot(fit_hist.history['val_loss'], label='Validation Loss')
plt.legend()
plt.show()

plt.plot(fit_hist.history['accuracy'], label='Training Accuracy')
plt.plot(fit_hist.history['val_accuracy'], label='Validation Accuracy')
plt.legend()
plt.show()