# -*- coding: utf-8 -*-
"""AI_exam03_keras_xor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BVeDhZrh5Cn2bgWwv4iaHVB9Sfw---Y0

XOR 문제!!!!!
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense
import matplotlib.pyplot as plt

training_data = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
target_data = np.array([[0], [1], [1], [0]])

model = Sequential()
model.add(Dense(32 ,input_dim=2, activation='relu')) # 텐서(출력) 32차원, 2차원 input, ReLU 활성함수 사용
model.add(Dense(1, activation='sigmoid')) # 텐서 1개, Sigmoid 활성함수 사용
model.compile(loss='mse', optimizer='adam', metrics=['binary_accuracy'])
model.summary()

fit_hist = model.fit(training_data, target_data, epochs=500, verbose=1)

plt.plot(fit_hist.history['loss'])
plt.show()

data = np.array([0, 0])
print(model.predict(data.reshape(1, 2))[0][0].round())

data = np.array([1, 0])
print(model.predict(data.reshape(1, 2))[0][0].round())

data = np.array([0, 1])
print(model.predict(data.reshape(1, 2))[0][0].round())

data = np.array([1, 1])
print(model.predict(data.reshape(1, 2))[0][0].round())

